### ISSUE TITLE
Commit data is not reliable

### ISSUE THREAD

**Issue by schlessera** [php-composter/php-composter#6]
The current method of retrieving the committed but not yet pushed data is unreliable, as it asks git about the names of files that were committed, but then uses the filesystem when manipulating these files.

The filesystem might already have additional changes applied to it, which were not yet `add`ed to the commit.

As an example: When using the PHPCS PSR-2 checker, it correctly detects issues upon trying to push a commit. However, if you then do changes to the filesystem, it PHPCS will get to see the changed files, and see that the errors were resolved. But a `push` will then push the versions that still contain the errors to the repository, as the last changes have not yet been `add`ed.

A possible workaround would be to generate a temporary copy of the files to be manipulated, to make sure that the exact committed version gets used.

**Comment by franz-josef-kaiser** [comment]
I suggest to get over handling Git by using a [reliable hierarchy](https://github.com/cpliakas/git-wrapper). It's easy to use, can handle any command, is Loggable, etc.
